#!/bin/bash

# @author Trey Rubino

ROOT_DIR="$(dirname "$0")/.."
REF_DIR="$ROOT_DIR/reference/files"
TEST_DIR="$ROOT_DIR/test/files"
REPORT="$ROOT_DIR/reports/$1"

rm -f "$REPORT"

echo "Reference vs. Hand-rolled Delta Report" >> "$REPORT"
echo Generated file name $1 >> "$REPORT"
echo "Generated on $(date)" >> "$REPORT"
echo "Generated by Trey Rubino" >> "$REPORT"
echo "-------------------------------------------------------------------" >> "$REPORT"

names=()
for f in "$TEST_DIR"/*.cl-lex "$TEST_DIR"/*.cl-ast "$TEST_DIR"/*.cl-type; do
  [[ -f "$f" ]] || continue
  base="$(basename "$f")"
  name="${base%%.cl-*}"
  skip=false
  for n in "${names[@]}"; do
    [[ "$n" == "$name" ]] && skip=true && break
  done
  $skip || names+=("$name")
done

IFS=$'\n' sorted_names=($(printf '%s\n' "${names[@]}" | sort))
unset IFS

for name in "${sorted_names[@]}"; do
  echo "$name"
  echo "Delta File Group: $name" >> "$REPORT"
  echo "-------------------------------------------------------------------" >> "$REPORT"

  for ext in cl-lex cl-ast cl-type; do
    test_file="$TEST_DIR/$name.$ext"
    ref_file="$REF_DIR/$name.$ext"

    if [[ ! -f "$test_file" && ! -f "$ref_file" ]]; then
      echo " $ext — Match (both missing)" >> "$REPORT"
      echo "" >> "$REPORT"
      continue
    fi
    if [[ ! -f "$test_file" ]]; then
      echo "Missing generated: $test_file" >> "$REPORT"
      echo "" >> "$REPORT"
      continue
    fi
    if [[ ! -f "$ref_file" ]]; then
      echo "Missing reference: $ref_file" >> "$REPORT"
      echo "" >> "$REPORT"
      continue
    fi

    diff_out=$(diff -u "$ref_file" "$test_file")
    if [[ -z "$diff_out" ]]; then
      echo " $ext — Match" >> "$REPORT"
    else
      echo " =$ext — Differences found:" >> "$REPORT"
      echo "$diff_out" >> "$REPORT"
    fi
    echo "" >> "$REPORT"
  done

  test_out="$TEST_DIR/$name.out"
  ref_out="$REF_DIR/$name.out"
  if [[ -f "$test_out" || -f "$ref_out" ]]; then
    if [[ -f "$test_out" && -f "$ref_out" ]]; then
      if diff -u "$ref_out" "$test_out" >/dev/null; then
        echo " out — Match" >> "$REPORT"
      else
        echo " =out — Differences found:" >> "$REPORT"
        echo " reference .out:" >> "$REPORT"
        cat "$ref_out" >> "$REPORT"
        echo "" >> "$REPORT"
        echo " hand-rolled .out:" >> "$REPORT"
        cat "$test_out" >> "$REPORT"
      fi
    else
      if [[ ! -f "$test_out" ]]; then
        echo "Missing generated .out: $test_out" >> "$REPORT"
      fi
      if [[ ! -f "$ref_out" ]]; then
        echo "Missing reference .out: $ref_out" >> "$REPORT"
      fi
    fi
    echo "" >> "$REPORT"
  fi

  echo "===================================================================" >> "$REPORT"
done
